---
- name: Start Mysql
  service: "name=mysql state=started enabled=yes sleep=5"

- name: Restart Mysql
  service: "name=mysql state=restarted sleep=5"

- name: Restart Apache
  become: yes
  service:
    name: apache2
    state: restarted

- name: Reload Apache
  become: yes
  service:
    name: apache2
    state: reloaded
